name: "Python Poetry automatic updates"
author: "@Apakottur"
description: "Create a PR that updates Python packages to latest possible versions, based on Poetry configuration files"
branding:
  icon: chevrons-up
  color: purple
inputs:
  base-branch:
    description: "Base branch, to run the updater on"
    required: false
    default: "main"
  python-version:
    description: "Python version for the updater"
    required: false
    default: "3.10"
  poetry-version:
    description: "Poetry version for the updater"
    required: false
    default: "1.1.12"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: pip install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Install Shpyx
      run: pip install shpyx
      shell: bash

    - name: Update packages
      run: ${{ github.action_path }}/main.py
      shell: bash

    - name: Check if any changes were made
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Create PR with updates
      if: steps.changes.outputs.changed == 1
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update Python packages
        branch: automated/package-updates
        branch-suffix: timestamp
        delete-branch: true
        title: Update Python packages
        base: ${{ inputs.base-branch }}