name: "Update Python Poetry packages"
author: "@Apakottur"
description: "Create a PR that updates Python packages to latest possible versions, based on Poetry configuration files"
branding:
  icon: chevrons-up
  color: purple
inputs:
  python-version:
    description: "Python version for the updater"
    required: false
    default: "3.10"
  poetry-version:
    description: "Poetry version for the updater"
    required: false
    default: "1.1.12"
  base-branch:
    description: "Git branch on which the updater is run"
    required: false
    default: "main"
  pr-body:
    description: "The body of the pull request"
    required: false
    default: "Automated changes by [update-python-poetry-packages](https://github.com/Apakottur/action-poetry-package-update) GitHub action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.base-branch }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: pip install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Install Shpyx
      run: pip install shpyx
      shell: bash

    - name: Update Python Poetry packages
      id: update-packages
      run: ${{ github.action_path }}/main.py
      shell: bash

    - name: Check if there are changes
      id: changes
      run: echo "::set-output name=changed::$(git status --porcelain | wc -l)"
      shell: bash

    - name: Create a PR with the updates
      if: steps.changes.outputs.changed > 0
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update Python packages
        branch: automated/package-updates
        branch-suffix: timestamp
        delete-branch: true
        title: Update Python packages
        body: ${{ inputs.pr-body }}
        base: ${{ inputs.base-branch }}
