[tool.poetry]
name = "action"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10" # Any version of Python 3.10
shpyx = "0.0.22"
tomlkit = "0.11.6"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"
