[tool.poetry]
name = "src"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.12"
shpyx = "0.0.32"
tomlkit = "0.13.2"
typer = "0.15.2"

[tool.poetry.group.dev.dependencies]
pytest = "8.3.5"
pytest-mock = "3.14.0"
pre-commit = "4.2.0"
