[tool.poetry]
name = "action"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11" # Any version of Python 3.11
shpyx = "0.0.25"
tomlkit = "0.11.8"

[tool.poetry.dev-dependencies]
pytest = "7.3.2"
pytest-mock = "3.11.1"
