[tool.poetry]
name = "src"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.12"
shpyx = "0.0.30"
tomlkit = "0.13.2"
typer = "0.12.5"

[tool.poetry.dev-dependencies]
pytest = "8.3.3"
pytest-mock = "3.14.0"
