[tool.poetry]
name = "action"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10" # Any version of Python 3.10
shpyx = "0.0.14"
tomlkit = "0.11.1"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
pytest-mock = "3.8.2"
