[tool.poetry]
name = "src"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11" # Any version of Python 3.11
shpyx = "0.0.25"
tomlkit = "0.12.3"

[tool.poetry.dev-dependencies]
pytest = "8.0.0"
pytest-mock = "3.12.0"
