# Run ourselves.
name: Update Python Poetry packages

on:
  pull_request:
    branches: [main]

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: Apakottur/action-poetry-package-update@main
        with:
          base-branch: main
