# Run unit tests.
name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest -c tests/pytest.ini
